version: '3.3'

services:
  database:
    container_name: database_symphony
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: symfony_test
      MYSQL_USER: symfony
      MYSQL_PASSWORD: 12345
    ports:
      - '3306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
  php:
    container_name: php_symphony
    restart: always
    build:
      context: ./php
    volumes:
      - ./app:/var/www/symfony_test
    depends_on:
      - database
    environment:
      DATABASE_URL: "mysql://symfony:12345@database:3306/symfony_test?serverVersion=5.7&charset=utf8mb4"
      APP_ENV: dev
      APP_DEBUG: 1
  nginx:
    container_name: nginx_symphony
    restart: always
    image: nginx:stable
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/symfony_test
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database